enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  '@agoric/ertp@*':
    dependencies:
      '@agoric/vat-data': '*'
  '@agoric/vat-data@*':
    dependencies:
      '@endo/init': '*'
